version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myapp
    volumes:
        - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    
  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
